// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwhazmordecjcrmqyaui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3aGF6bW9yZGVjamNybXF5YXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDM1NTgsImV4cCI6MjA2NzAxOTU1OH0.0SVLbfRem2-ASdmFKG_CtLHEZ0HTRvVK21YEIaZGVgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});